# Base configs
baseurl: ""

# UI configs
title: "Kenil Maniya"
author: "Kenil Maniya"
about: "COMPUTER ENGINEER"
social_urls:
  facebook: "https://www.facebook.com/maniya.kenil@gmail.com"
  twitter: ""
  instagram: "https://www.instagram.com/__kingsman._"
  github: ""
